<?php
declare(strict_types=1);
final class VehiculoRepositoryMySQL implements SaveVehiculoPort, UpdateVehiculoPort, GetVehiculoByIdPort, GetVehiculoByPlacaPort, GetAllVehiculosPort, DeleteVehiculoPort
{
    private PDO $pdo; private VehiculoPersistenceMapper $mapper;
    public function __construct(PDO $pdo, VehiculoPersistenceMapper $mapper){$this->pdo=$pdo;$this->mapper=$mapper;}
    public function save(VehiculoModel $vehiculo): VehiculoModel { $d=$this->mapper->fromModelToDto($vehiculo)->all(); $sql='INSERT INTO vehiculos (id,placa,marca,modelo,version,color,num_puestos,num_puertas,combustible,kilometros,cilindraje,categoria,created_at,updated_at) VALUES (:id,:placa,:marca,:modelo,:version,:color,:numPuestos,:numPuertas,:combustible,:kilometros,:cilindraje,:categoria,NOW(),NOW())'; $st=$this->pdo->prepare($sql); $st->execute([':id'=>$d['id'],':placa'=>$d['placa'],':marca'=>$d['marca'],':modelo'=>$d['modelo'],':version'=>$d['version'],':color'=>$d['color'],':numPuestos'=>$d['numPuestos'],':numPuertas'=>$d['numPuertas'],':combustible'=>$d['combustible'],':kilometros'=>$d['kilometros'],':cilindraje'=>$d['cilindraje'],':categoria'=>$d['categoria']]); return $this->getById(new VehiculoId($d['id'])); }
    public function update(VehiculoModel $vehiculo): VehiculoModel { $d=$this->mapper->fromModelToDto($vehiculo)->all(); $sql='UPDATE vehiculos SET placa=:placa,marca=:marca,modelo=:modelo,version=:version,color=:color,num_puestos=:numPuestos,num_puertas=:numPuertas,combustible=:combustible,kilometros=:kilometros,cilindraje=:cilindraje,categoria=:categoria,updated_at=NOW() WHERE id=:id'; $st=$this->pdo->prepare($sql); $st->execute([':id'=>$d['id'],':placa'=>$d['placa'],':marca'=>$d['marca'],':modelo'=>$d['modelo'],':version'=>$d['version'],':color'=>$d['color'],':numPuestos'=>$d['numPuestos'],':numPuertas'=>$d['numPuertas'],':combustible'=>$d['combustible'],':kilometros'=>$d['kilometros'],':cilindraje'=>$d['cilindraje'],':categoria'=>$d['categoria']]); return $this->getById(new VehiculoId($d['id'])); }
    public function getById(VehiculoId $vehiculoId): ?VehiculoModel { $st=$this->pdo->prepare('SELECT * FROM vehiculos WHERE id=:id LIMIT 1'); $st->execute([':id'=>$vehiculoId->value()]); $row=$st->fetch(); return $row===false?null:$this->mapper->fromRowToModel($row); }
    public function getByPlaca(VehiculoPlaca $placa): ?VehiculoModel { $st=$this->pdo->prepare('SELECT * FROM vehiculos WHERE placa=:placa LIMIT 1'); $st->execute([':placa'=>$placa->value()]); $row=$st->fetch(); return $row===false?null:$this->mapper->fromRowToModel($row); }
    public function getAll(): array { $rows=$this->pdo->query('SELECT * FROM vehiculos ORDER BY marca ASC, modelo ASC')->fetchAll(); return $this->mapper->fromRowsToModels($rows); }
    public function delete(VehiculoId $vehiculoId): void { $st=$this->pdo->prepare('DELETE FROM vehiculos WHERE id=:id'); $st->execute([':id'=>$vehiculoId->value()]); }
}
